name: Deploy to Github Pages
on:
  push:
    branches:
      - master
      - ci/gh-pages-deploy
permissions:
  contents: write

jobs:
  deploy_to_gh:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install pnpm â¤ï¸ï¸
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }} â¤ï¸ï¸
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install and Build Frontend ğŸ”§
        run: |
          pnpm install
          pnpm build
        env:
          VITE_BASE_URL: '/project-x'

      - name: Github Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
