name: Cleanup Preview on Github Pages
on:
  pull_request:
    types: [opened, synchronize, reopened, closed] #TODO: should only be closed
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  pull-requests: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: gh-pages

      - name: Remove Preview Folder ğŸ—‘ï¸
        run: |
          git rm -r preview/${{ github.event.number }}
          git commit -m "Remove preview folder for PR#${{ github.event.number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
